version: "3.8"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt_app
    volumes:
      - .:/src
    networks:
      - nuxt_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nuxt
    networks:
      - nuxt_network

networks:
  nuxt_network:
